version: "1.0"
stages:
  - "clone"
  - "versioning"
  - "testimage"
  - "test"
  - "reporting"
  - "build"
  - "integration"
  - "push"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "sushant08/cf-python"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  Tagtest:
    title: pushing git sha to version
    image: alpine
    stage: 'versioning'
    commands:
      - echo $CF_REVISION
      - echo $CF_REVISION > ${{CF_VOLUME_PATH}}/cf-python/version
      - cat ${{CF_VOLUME_PATH}}/cf-python/version
      - ls -l ${{CF_VOLUME_PATH}}/cf-python
  UnitTestDockerImage:
    title: Building Test image
    type: build
    stage: 'testimage'
    image_name: test-image
    tag: 'master'
    dockerfile: Dockerfile.test
  UnitTests:
    title: Running Unit tests
    stage: test
    image: '${{UnitTestDockerImage}}'
    commands:
      - python test_basic.py
      - py.test test_basic.py --alluredir ${{CF_VOLUME_PATH}}/allure-results
  reporting_step:
    title: Generate test reporting
    image: codefresh/cf-docker-test-reporting
    working_directory: '${{CF_VOLUME_PATH}}'
    environment:
      - BUCKET_NAME=kops08
      - CF_STORAGE_INTEGRATION=amazon
    stage: "reporting"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "833087016060.dkr.ecr.us-east-1.amazonaws.com/test"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  approval_for_push:
    type: "pending-approval"
    title: "Should we run push"
    when:
      branch:
        only:
          - "master"
    stage: "push"
  push:
    title: "Pushing image to cfcr"
    type: "push"
    image_name: "test"
    registry: "test"
    candidate: "${{build}}"
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "${{CF_REVISION}}"
    stage: "push" 
  StoreChart:
    title: Storing Helm chart
    stage: deploy
    image: 'codefresh/cfstep-helm:2.12.3'
    working_directory: cf-python/
    environment:
      - ACTION=push
      - CHART_REF=.
      - CHART_REPO_URL=s3://codefresh-test/codefresh
      - RELEASE_NAME=first-chart
