version: "1.0"
stages:
  - "clone"
  - "versioning"
  - "testimage"
  - "test"
  - "build"
  - "integration"
  - "push"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "sushant08/cf-python"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  Tagtest:
    title: pushing git sha to version
    image: alpine
    stage: 'versioning'
    commands:
      - echo $CF_REVISION
      - echo $CF_REVISION > ${{CF_VOLUME_PATH}}/cf-python/version
      - cat ${{CF_VOLUME_PATH}}/cf-python/version
      - ls -l ${{CF_VOLUME_PATH}}/cf-python
  UnitTestDockerImage:
    title: Building Test image
    type: build
    stage: 'testimage'
    image_name: test-image
    tag: 'master'
    dockerfile: Dockerfile.test
  UnitTests:
    title: Running Unit tests
    stage: test
    image: '${{UnitTestDockerImage}}'
    commands:
      - python test_basic.py
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "sushant08/cf-python"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  approval_for_push:
    type: "pending-approval"
    title: "Should we run push"
    when:
      branch:
        only:
          - "master"
    stage: "push"
  push:
    title: "Pushing image to cfcr"
    type: "push"
    image_name: "sushant08/cf-python"
    registry: "cfcr"
    candidate: "${{build}}"
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "${{CF_REVISION}}"
    stage: "push"
  
  deploy_ecs:
    image: codefresh/cf-deploy-ecs 
    commands:
      - cfecs-update --image-name sushant08/cf-python --image-tag '${{CF_BRANCH_TAG_NORMALIZED}}' us-east-1 test codefresh
    environment:
      - AWS_ACCESS_KEY_ID=${{AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{AWS_SECRET_ACCESS_KEY}}
    when:
      branch:
        only:
          - master
    stage: "deploy"
