FROM ubuntu:latest

RUN mkdir /test

COPY app.py /test
COPY test_basic.py /test
COPY coverage.sh /test

RUN apt-get update \
  && apt-get install python  -y \
  && apt-get install -y python-pip \
  && pip install Flask \
  && pip install jinja2 \
  && pip install markupsafe

WORKDIR /test