apiVersion: v1
kind: Pod
metadata:
  name: '{{- printf "%s-%s-%s" .Release.Name .Chart.Name ( .Values.parent | default "base" ) | trunc 63 | trimSuffix "-" -}}'
spec:
  containers:
  - image: 
    name: '{{ .Chart.Name }}'
    command: ['/bin/sh', '-c', 'while true; do echo {{ .Values.message }}; sleep 5; done']